### ISSUE TITLE
Add Metrics Tracking

### ISSUE THREAD

**Issue by petioptrv** [petioptrv/bot-letter#2]
# Why

The cost per newsletter needs to be tracked and analyzed.

# What

- [x] Increase the time articles are kept in Redis to one week.
- [ ] ~Ensure that the `NewsletterArticles` table (see below) holds at most one week of data.~
- [x] Add logic to store the current newsletter creator configuration version on celery app startup.
  - It must auto-detect if the current configuration is already in the `NewsletterGenerationConfig` table (see below).
  - If it is, then load the ID of the config from the table and store it locally.
  - If not, add a new entry and store that new ID locally.
- [x] Add the following SQL tables:

### NewsletterGenerationConfig

- Columns
  - The columns necessary to store the values of the config attributes

### NewsletterIssues

- Columns
  - Issue ID
  - Subscription ID
  - Timestamp

### IssueArticles

- Columns
  - Issue ID
  - Article ID

### IssueMetrics

- Columns
  - Issue ID
  - Newsletter generation config ID
  - Time it took to generate

### TokenCosts

- Columns
  - Issue ID
  - Article ID
  - Step (of the generation process)
  - OpenAI token cost
